Repository five-io/logistics, pull requests merged in 2025-03, with the labels that each got.

#2 [env] eureka server
  .idea/logistics.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  eureka-server/.gitattributes
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.jar
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/settings.gradle
  eureka-server/src/main/java/com/msa/fiveio/eureka_server/EurekaServerApplication.java
  eureka-server/src/main/resources/application.properties
  eureka-server/src/test/java/com/msa/fiveio/eureka_server/EurekaServerApplicationTests.java
Labels: env

#9 Feat/#4 [Hub] Create 생성
  config/src/main/resources/config-repo/aiinterlock-local.yml
  config/src/main/resources/config-repo/company-local.yml
  config/src/main/resources/config-repo/delivery-local.yml
  config/src/main/resources/config-repo/hub-local.yml
  config/src/main/resources/config-repo/hub-service-local.yml
  config/src/main/resources/config-repo/order-local.yml
  config/src/main/resources/config-repo/slack-local.yml
  config/src/main/resources/config-repo/user-local.yml
  gateway/src/main/resources/application.yml
  gateway/src/main/resources/bootstrap.yml
  hub/build.gradle
  hub/src/main/java/com/msa/fiveio/hub/HubApplication.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacade.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/client/KakaoClient.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/configuration/KakaoConfig.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepositoryCustom.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepositoryCustomImpl.java
  hub/src/main/java/com/msa/fiveio/hub/model/entity/Hubs.java
  hub/src/main/java/com/msa/fiveio/hub/model/repository/HubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/DocumentDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/HubsRequestDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/HubsResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/KakaoResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/MetaDto.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/bootstrap.yml
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: feature

#11 [Hubs] Read/Update Api 생성
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacade.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/model/entity/Hubs.java
  hub/src/main/java/com/msa/fiveio/hub/model/repository/HubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/HubsRequestDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/HubsResponseDto.java
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: feature

#13 [Slack] Create API 생성
  settings.gradle
  slack/build.gradle
  slack/src/main/java/com/msa/fiveio/slack/SlackApplication.java
  slack/src/main/java/com/msa/fiveio/slack/application/service/SlackMessagesService.java
  slack/src/main/java/com/msa/fiveio/slack/model/entity/SlackMessages.java
  slack/src/main/java/com/msa/fiveio/slack/model/repository/SlackMessagesRepository.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlackMessagesController.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlackMessagesCreateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlackMessagesCreateResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/mapper/SlackMessagesMapper.java
  slack/src/main/resources/application.yml
Labels: feature

#15 [Slack] Update Api 생성
  slack/src/main/java/com/msa/fiveio/slack/application/service/SlackMessagesService.java
  slack/src/main/java/com/msa/fiveio/slack/application/service/SlacksService.java
  slack/src/main/java/com/msa/fiveio/slack/infrastructure/exception/BusinessLogicException.java
  slack/src/main/java/com/msa/fiveio/slack/model/entity/Slacks.java
  slack/src/main/java/com/msa/fiveio/slack/model/repository/SlacksRepository.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlackMessagesController.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlacksController.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksCreateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksCreateResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksUpdateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksUpdateResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/mapper/SlackMessagesMapper.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/mapper/SlacksMapper.java
Labels: feature

#18 [Common] Common 모듈 및 Auditing 설정(날짜만)
  build.gradle
  common/build.gradle
  common/gradle/wrapper/gradle-wrapper.properties
  common/src/main/java/com/msa/fiveio/common/auditing/BaseEntity.java
  common/src/main/java/com/msa/fiveio/common/config/JpaAuditingConfig.java
  common/src/main/resources/application.properties
  gateway/gradle/wrapper/gradle-wrapper.properties
  hub/gradle/wrapper/gradle-wrapper.properties
  hub/src/main/java/com/msa/fiveio/hub/HubApplication.java
  hub/src/main/java/com/msa/fiveio/hub/model/entity/Hubs.java
  settings.gradle
Labels: feature

#23 [Hub]공통 Exception, Swagger 설정
  common/src/main/java/com/msa/fiveio/common/config/QueryDslConfig.java
  common/src/main/java/com/msa/fiveio/common/exception/CustomException.java
  common/src/main/java/com/msa/fiveio/common/exception/ErrorCode.java
  common/src/main/java/com/msa/fiveio/common/exception/ErrorResponse.java
  common/src/main/java/com/msa/fiveio/common/exception/ExceptionHandlerController.java
  common/src/main/java/com/msa/fiveio/common/exception/domain/HubErrorCode.java
  config/build.gradle
  config/src/main/resources/config-repo/ai-service-local.yml
  config/src/main/resources/config-repo/application-common.yml
  config/src/main/resources/config-repo/comp-service-local.yml
  config/src/main/resources/config-repo/delivery-serivce-local.yml
  config/src/main/resources/config-repo/gateway-service-local.yml
  config/src/main/resources/config-repo/hub-service-local.yml
  config/src/main/resources/config-repo/order-service-local.yml
  config/src/main/resources/config-repo/slack-service-local.yml
  config/src/main/resources/config-repo/user-service-local.yml
  eureka-server/build.gradle
  gateway/build.gradle
  gateway/src/main/java/com/spring_cloud/client/gateway/CustomPreFilter.java
  gateway/src/main/resources/application.yml
  hub/build.gradle
  hub/src/main/java/com/msa/fiveio/hub/HubApplication.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/configuration/SwaggerConfig.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/HubsMapper.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/SearchResponseDtos.java
  hub/src/main/resources/application.yml
  settings.gradle
Labels: feature

#27 [Company] Create ApI 생성
  company/build.gradle
  company/src/main/java/com/msa/fiveio/company/CompanyApplication.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacade.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacadeImpl.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyService.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/msa/fiveio/company/infrastructure/repository/JPACompanysRepository.java
  company/src/main/java/com/msa/fiveio/company/infrastructure/repository/JPACompanysRepositoryCustom.java
  company/src/main/java/com/msa/fiveio/company/infrastructure/repository/JPACompanysRepositoryCustomImpl.java
  company/src/main/java/com/msa/fiveio/company/model/entity/Companys.java
  company/src/main/java/com/msa/fiveio/company/model/entity/CompanysType.java
  company/src/main/java/com/msa/fiveio/company/model/repository/CompanysRepository.java
  company/src/main/java/com/msa/fiveio/company/presentation/controller/CompanysController.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/CompanyRequestDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/CompanyResponseDto.java
  company/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  settings.gradle
Labels: feature

#29 [Company] 업체단건조회 API 생성
  common/src/main/java/com/msa/fiveio/common/exception/domain/CompanysErrorCode.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacade.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacadeImpl.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyService.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/msa/fiveio/company/model/repository/CompanysRepository.java
  company/src/main/java/com/msa/fiveio/company/presentation/controller/CompanysController.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/CompanyCreateRequestDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/CompanyCreateResponseDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/CompanyGetResponseDto.java
Labels: feature

#41 [Common]Swagger 수정
  gateway/src/main/resources/application.yml
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/configuration/SwaggerConfig.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepositoryCustomImpl.java
Labels: env

#34 [Slack] Search Api 생성
  slack/src/main/java/com/msa/fiveio/slack/application/service/SlacksService.java
  slack/src/main/java/com/msa/fiveio/slack/model/repository/SlacksQueryRepository.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlacksController.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksSearchRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksSearchResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/mapper/SlacksMapper.java
Labels: feature

#43 [Slack] Facade, Usecase 적용
  common/src/main/java/com/msa/fiveio/common/config/JpaAuditingConfig.java
  common/src/main/java/com/msa/fiveio/common/config/QueryDslConfig.java
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacade.java
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacadeImpl.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksService.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksServiceImpl.java
  slack/src/main/java/com/msa/fiveio/slack/model/repository/SlacksQueryRepository.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlacksController.java
  slack/src/test/java/com/msa/fiveio/slack/httpClient/Slacks.http
Labels: feature

#44 [Delivery] 배송 생성 구현
  delivery/build.gradle
  delivery/src/main/java/com/msa/fiveio/delivery/DeliveryApplication.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacade.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/DeliveryManagers.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/configuration/DeliveryQueueConfig.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/messaging/DeliveryCreatedCompletedMessage.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/messaging/DeliveryMessageListener.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/repository/JpaDeliveryRepository.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/Delivery.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryFactory.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRoute.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRouteDetails.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/Recipient.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/enums/DeliveryRouteStatus.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/enums/DeliveryStatus.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/repository/DeliveryRepository.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/dto/request/DeliveryCreateRequestDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/mapper/DeliveryMapper.java
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/msa/fiveio/delivery/DeliveryApplicationTests.java
  settings.gradle
Labels: feature

#48 [Slack] Common Errorcode 적용
  common/src/main/java/com/msa/fiveio/common/exception/domain/SlackErrorCode.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksServiceImpl.java
  slack/src/main/java/com/msa/fiveio/slack/infrastructure/exception/BusinessLogicException.java
  slack/src/main/java/com/msa/fiveio/slack/model/entity/Slacks.java
Labels: feature

#52 [Auth]인가 구현
  common/src/main/java/com/msa/fiveio/common/config/JpaAuditingConfig.java
  common/src/main/java/com/msa/fiveio/common/config/QueryDslConfig.java
  common/src/main/java/com/msa/fiveio/common/exception/domain/AuthErrorCode.java
  common/src/main/java/com/msa/fiveio/common/redis/RedisService.java
  gateway/build.gradle
  gateway/src/main/java/com/spring_cloud/client/gateway/CustomPreFilter.java
  gateway/src/main/java/com/spring_cloud/client/gateway/GatewayApplication.java
  gateway/src/main/java/com/spring_cloud/client/gateway/SecurityConfig.java
  gateway/src/main/java/com/spring_cloud/client/gateway/SwaggerConfig.java
  gateway/src/main/java/com/spring_cloud/client/gateway/exception/AccessTokenExpiredException.java
  gateway/src/main/java/com/spring_cloud/client/gateway/exception/BaseException.java
  gateway/src/main/java/com/spring_cloud/client/gateway/exception/NotExistsAuthorization.java
  gateway/src/main/resources/application.yml
Labels: feature

#58 [feat #46] Order 엔티티 기반 주문 응답 Dto 반환 메서드 Mapper로 이동
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/model/entity/Order.java
  order/src/main/java/com/msa/fiveio/order/presentation/mapper/OrderMapper.java
Labels: feature

#51 [User] User Create
  common/src/main/java/com/msa/fiveio/common/config/JpaAuditingConfig.java
  common/src/main/java/com/msa/fiveio/common/config/QueryDslConfig.java
  common/src/main/java/com/msa/fiveio/common/exception/domain/UserErrorCode.java
  settings.gradle
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksServiceImpl.java
  user/build.gradle
  user/src/main/java/com/msa/fiveio/user/UserApplication.java
  user/src/main/java/com/msa/fiveio/user/application/UsersService.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/config/AppConfig.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/security/JwtUtil.java
  user/src/main/java/com/msa/fiveio/user/model/entity/Users.java
  user/src/main/java/com/msa/fiveio/user/model/entity/UsersFactory.java
  user/src/main/java/com/msa/fiveio/user/model/entity/UsersRoleEnum.java
  user/src/main/java/com/msa/fiveio/user/model/entity/enums/UsersRoleEnum.java
  user/src/main/java/com/msa/fiveio/user/model/repository/UsersRepository.java
  user/src/main/java/com/msa/fiveio/user/presentation/controller/UsersController.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersLoginRequestDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersProfileDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersSignUpRequestDto.java
  user/src/main/resources/application.yml
Labels: feature

#59 [Order] 주문 단일 조회
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/facade/OrdersFacade.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/messaging/dto/DeliveryCreateRequest.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/repository/JpaOrderRepository.java
  order/src/main/java/com/msa/fiveio/order/model/entity/Order.java
  order/src/main/java/com/msa/fiveio/order/model/repository/OrderRepository.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
  order/src/main/java/com/msa/fiveio/order/presentation/dto/request/OrderCreateRequestDto.java
  order/src/main/java/com/msa/fiveio/order/presentation/dto/response/OrderResponseDto.java
  order/src/main/java/com/msa/fiveio/order/presentation/mapper/OrderMapper.java
Labels: feature

#40 [Company] Delete API 생성
  company/src/main/java/com/msa/fiveio/company/CompanyApplication.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacade.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacadeImpl.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyService.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/msa/fiveio/company/model/entity/Companys.java
  company/src/main/java/com/msa/fiveio/company/model/repository/CompanysRepository.java
  company/src/main/java/com/msa/fiveio/company/presentation/controller/CompanysController.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/CompanyCreateResponseDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/CompanyGetResponseDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/mapper/CompanysMapper.java
  hub/src/main/java/com/msa/fiveio/hub/model/entity/Hubs.java
Labels: feature

#55 [Company] Update API 생성
  company/build.gradle
  company/src/main/java/com/msa/fiveio/company/CompanyApplication.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacade.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacadeImpl.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyService.java
  company/src/main/java/com/msa/fiveio/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/msa/fiveio/company/infrastructure/repository/JPACompanysRepository.java
  company/src/main/java/com/msa/fiveio/company/infrastructure/repository/JPACompanysRepositoryCustom.java
  company/src/main/java/com/msa/fiveio/company/infrastructure/repository/JPACompanysRepositoryCustomImpl.java
  company/src/main/java/com/msa/fiveio/company/model/entity/Companys.java
  company/src/main/java/com/msa/fiveio/company/model/entity/CompanysType.java
  company/src/main/java/com/msa/fiveio/company/model/repository/CompanysRepository.java
  company/src/main/java/com/msa/fiveio/company/presentation/controller/CompanysController.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/request/CompanyCreateRequestDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/request/CompanyUpdateRequestDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/response/CompanyCreateResponseDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/response/CompanyGetResponseDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/dto/response/CompanyUpdateResponseDto.java
  company/src/main/java/com/msa/fiveio/company/presentation/mapper/CompanysMapper.java
  company/src/test/java/com/msa/fiveio/company/Company.http
  config/src/main/resources/config-repo/company-local.yml
  config/src/main/resources/config-repo/delivery-local.yml
  config/src/main/resources/config-repo/hub-local.yml
  config/src/main/resources/config-repo/order-local.yml
  config/src/main/resources/config-repo/slack-local.yml
  config/src/main/resources/config-repo/user-local.yml
Labels: feature

#62 [Order] 배송 서비스 통신 방식 변경
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/facade/OrdersFacade.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/DeliveryClient.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/request/DeliveryCreateRequestDto.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/response/CompanyResponseDto.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/response/DeliveryCreateResponseDto.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/configuration/OrderQueueConfig.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/messaging/OrderMessageListener.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/messaging/dto/DeliveryCreatedMessage.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/repository/JpaOrderRepositoryCustomImpl.java
  order/src/main/java/com/msa/fiveio/order/model/entity/Order.java
  order/src/main/java/com/msa/fiveio/order/model/entity/OrderFactory.java
  order/src/main/java/com/msa/fiveio/order/presentation/dto/request/OrderCreateRequestDto.java
  order/src/main/java/com/msa/fiveio/order/presentation/dto/request/OrderSearchRequestDto.java
  order/src/main/java/com/msa/fiveio/order/presentation/mapper/OrderMapper.java
  order/src/main/resources/application.yml
Labels: feature

#70 [Order] CompanyClient 파일 제거
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/CompanyClient.java
Labels: refactoring

#73 [Auth] 인가 및 토큰 발행
  common/src/main/java/com/msa/fiveio/common/redis/RedisService.java
  gateway/src/main/java/com/spring_cloud/client/gateway/CustomPreFilter.java
  gateway/src/main/java/com/spring_cloud/client/gateway/GatewayApplication.java
  gateway/src/main/java/com/spring_cloud/client/gateway/SecurityConfig.java
  gateway/src/main/resources/application.yml
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/configuration/SwaggerConfig.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepositoryCustomImpl.java
  hub/src/main/java/com/msa/fiveio/hub/model/entity/Hubs.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/HubsMapper.java
  init.sql
  user/src/main/java/com/msa/fiveio/user/application/UsersService.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/config/AppConfig.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/AuthSecurityConfig.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/SwaggerConfig.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/JwtAuthenticationFilter.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/JwtProperties.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/JwtUtil.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/UserDetailsImpl.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/UserDetailsServiceImpl.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/repository/JpaUserRepository.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/security/JwtUtil.java
  user/src/main/java/com/msa/fiveio/user/model/entity/Users.java
  user/src/main/java/com/msa/fiveio/user/model/entity/UsersFactory.java
  user/src/main/java/com/msa/fiveio/user/model/entity/UsersRoleEnum.java
  user/src/main/java/com/msa/fiveio/user/model/repository/UsersRepository.java
  user/src/main/java/com/msa/fiveio/user/presentation/controller/UsersController.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UserDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersProfileDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersSignUpRequestDto.java
  user/src/test/java/com/msa/fiveio/user/httpClient/Users.http
Labels: feature

#77 [Order] Swagger 설정 및 httpClient 추가
  order/build.gradle
  order/src/main/java/com/msa/fiveio/order/infrastructure/configuration/SwaggerConfig.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
  order/src/test/java/com/msa/fiveio/order/httpClient/Orders.http
Labels: feature

#79 [Delivery] Swagger 설정 및 Http Client 추가
  delivery/build.gradle
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/configuration/SwaggerConfig.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
  delivery/src/test/java/com/msa/fiveio/delivery/httpClient/Delivery.http
Labels: feature

#83 [Delivery] 배송 단일 조회
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacade.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
  delivery/src/test/java/com/msa/fiveio/delivery/httpClient/Delivery.http
Labels: feature

#85 [Order] Order 서비스 리팩토링
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/repository/JpaOrderRepository.java
  order/src/main/java/com/msa/fiveio/order/model/entity/Order.java
  order/src/main/java/com/msa/fiveio/order/model/repository/OrderRepository.java
  order/src/main/java/com/msa/fiveio/order/presentation/dto/request/OrderCreateRequestDto.java
  order/src/main/java/com/msa/fiveio/order/presentation/mapper/OrderMapper.java
Labels: refactoring

#88 [Hub] 허브 간 이동경로 Create Api
  gateway/src/main/java/com/spring_cloud/client/gateway/CustomPreFilter.java
  gateway/src/main/resources/application.yml
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubRouteFacade.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubRouteFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacade.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubRouteService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubRouteServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/client/KakaoClient.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/client/KakaoMobility.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/configuration/KakaoConfig.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepositoryCustom.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepositoryCustomImpl.java
  hub/src/main/java/com/msa/fiveio/hub/model/entity/HubRoute.java
  hub/src/main/java/com/msa/fiveio/hub/model/entity/Hubs.java
  hub/src/main/java/com/msa/fiveio/hub/model/repository/HubRouteRepository.java
  hub/src/main/java/com/msa/fiveio/hub/model/repository/HubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubRouteController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/HubsRequestDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/HubsResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubRoutes/DirectionsResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubRoutes/HubRouteListResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubRoutes/HubRouteRequestDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubRoutes/HubRouteResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/DocumentDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/HubsRequestDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/HubsResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/KakaoResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/MetaDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/SearchResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/HubsMapper.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/SearchResponseDtos.java
  hub/src/test/java/com/msa/fiveio/hub/httpClient/HubRoute.http
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: feature

#92 [Hub]이동경로 생성
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/enums/DeliveryRouteStatus.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubRouteFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacade.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubRouteService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubRouteServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/model/repository/HubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/InitSetting.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/HubsRequestDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/HubsResponseDto.java
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: feature

#89 [Order] 주문 수정 API 생성
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/facade/OrdersFacade.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/model/entity/Order.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
  order/src/main/java/com/msa/fiveio/order/presentation/dto/request/OrderUpdateRequestDto.java
  order/src/test/java/com/msa/fiveio/order/httpClient/Orders.http
Labels: feature

#94 [Ai] Create API 생성
  ai/build.gradle
  ai/src/main/java/com/msa/fiveio/ai/AiApplication.java
  ai/src/main/java/com/msa/fiveio/ai/application/facade/AisFacade.java
  ai/src/main/java/com/msa/fiveio/ai/application/facade/AisFacadeImpl.java
  ai/src/main/java/com/msa/fiveio/ai/application/usecase/AisService.java
  ai/src/main/java/com/msa/fiveio/ai/application/usecase/AisServiceImpl.java
  ai/src/main/java/com/msa/fiveio/ai/infrastructure/client/GeminiClient.java
  ai/src/main/java/com/msa/fiveio/ai/infrastructure/configuration/GeminiConfig.java
  ai/src/main/java/com/msa/fiveio/ai/infrastructure/configuration/SwaggerConfig.java
  ai/src/main/java/com/msa/fiveio/ai/presentation/controller/AisController.java
  ai/src/main/java/com/msa/fiveio/ai/presentation/dto/AisCreateRequestDto.java
  ai/src/main/java/com/msa/fiveio/ai/presentation/dto/GeminiRequestDto.java
  ai/src/main/java/com/msa/fiveio/ai/presentation/dto/GeminiResponseDto.java
  ai/src/main/resources/application.yml
Labels: feature

#97 [Auth] API 권한 설정을 위한 어노테이션과 AOP 추가
  common/src/main/java/com/msa/fiveio/common/annotation/ApiPermission.java
  common/src/main/java/com/msa/fiveio/common/aop/PermissionCheckAspect.java
  gateway/src/main/java/com/spring_cloud/client/gateway/CustomPreFilter.java
  order/src/main/java/com/msa/fiveio/order/OrderApplication.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
Labels: feature

#102 [Hub] 최단경로 조회
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubRouteFacade.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubRouteFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacade.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubRouteService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubRouteServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubRouteRepository.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/repository/JpaHubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/model/repository/HubRouteRepository.java
  hub/src/main/java/com/msa/fiveio/hub/model/repository/HubsRepository.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubRouteController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/InitSetting.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/RegionMap.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubRoutes/HubRouteResponseDto.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/HubRouteDtos.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/HubsMapper.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/mapper/HubsResponseDtos.java
  hub/src/test/java/com/msa/fiveio/hub/httpClient/HubRoute.http
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: feature

#103 [Slack] Create Api 리팩토링
  slack/src/main/java/com/msa/fiveio/slack/model/entity/Slacks.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksCreateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/mapper/SlacksMapper.java
Labels: refactoring

#105 [Ai] Create API 생성
  ai/build.gradle
  ai/src/main/java/com/msa/fiveio/ai/AiApplication.java
  ai/src/main/resources/application.yml
  settings.gradle
Labels: feature

#109 [Delivery] Delivery 엔티티 생성 방법 변경
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/Delivery.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryFactory.java
Labels: refactoring

#110 [Delivery] 배송 생성 시 슬랙 메시지 요청
  delivery/src/main/java/com/msa/fiveio/delivery/DeliveryApplication.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/ExternalService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/ExternalServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/SlackClient.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/DeliveryManagers.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/request/SlacksCreateRequestDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/response/HubsResponseDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/response/SlacksCreateResponseDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/dto/request/DeliveryCreateRequestDto.java
Labels: feature

#113 [Delivery] 불필요한 주석 제거
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
Labels: refactoring

#115 [Delivery] 배송경로 생성
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryRouteFacade.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryRouteFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryRouteService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryRouteServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/RouteRequestDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/RouteResponseDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/repository/JpaDeliveryRouteRepository.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRoute.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRouteDetails.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryRouteController.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/dto/request/CreateDeliveryRouteRequest.java
  delivery/src/test/java/com/msa/fiveio/delivery/httpClient/DeliveryRoute.http
Labels: feature

#117 [Slack] Slack 상태 변경 API
  ai/build.gradle
  ai/src/main/java/com/msa/fiveio/ai/presentation/dto/AisCreateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacade.java
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacadeImpl.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksService.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksServiceImpl.java
  slack/src/main/java/com/msa/fiveio/slack/model/entity/SendStatus.java
  slack/src/main/java/com/msa/fiveio/slack/model/entity/Slacks.java
  slack/src/main/java/com/msa/fiveio/slack/model/repository/SlacksRepository.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlacksController.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksCreateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksUpdateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksUpdateResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/mapper/SlacksMapper.java
Labels: feature

#120 [Order] 주문 취소 API 생성
  common/src/main/java/com/msa/fiveio/common/auditing/BaseEntity.java
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/facade/OrdersFacade.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/DeliveryClient.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/request/DeliveryCreateRequestDto.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/response/CompanyResponseDto.java
  order/src/main/java/com/msa/fiveio/order/model/entity/Order.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
Labels: feature

#121 [Delivery]배송 상태 변경
  common/src/main/java/com/msa/fiveio/common/auditing/BaseEntity.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryRouteFacade.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryRouteFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryRouteService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryRouteServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/request/RouteRequestDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/infrastructure/client/dto/response/RouteResponseDto.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/Delivery.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRoute.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRouteDetails.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryRouteController.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/dto/DeliveryRouteResponse.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/dto/request/CreateDeliveryRouteRequest.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/dto/request/DeliveryRouteRequest.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/mapper/DeliveryMapper.java
  delivery/src/test/java/com/msa/fiveio/delivery/httpClient/DeliveryRoute.http
  gateway/src/main/java/com/spring_cloud/client/gateway/SwaggerConfig.java
  gateway/src/main/resources/application.yml
  hub/src/main/java/com/msa/fiveio/hub/HubApplication.java
  hub/src/main/java/com/msa/fiveio/hub/infrastructure/configuration/SwaggerConfig.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubRouteController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/InitSetting.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/dto/hubs/HubsRequestDto.java
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: feature

#123 [TEST] HttpClient 통합테스트
  Test/IntegrationTest.http
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryRouteController.java
  hub/src/main/java/com/msa/fiveio/hub/application/facade/HubsFacadeImpl.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsService.java
  hub/src/main/java/com/msa/fiveio/hub/application/usecase/HubsServiceImpl.java
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: test

#125 [Order] 상품 서비스에 상품 정보 조회 요청
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/request/DeliveryCreateRequestDto.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/response/ProductResponseDto.java
Labels: feature

#127 [Delivery] 배송 상태 조회
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacade.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/repository/DeliveryRepository.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
Labels: feature

#119 [Slack] Slack 조회, 검색, 삭제 Refactoring
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacade.java
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacadeImpl.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksService.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksServiceImpl.java
  slack/src/main/java/com/msa/fiveio/slack/model/entity/Slacks.java
  slack/src/main/java/com/msa/fiveio/slack/model/repository/SlacksQueryRepository.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlacksController.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksCreateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksDeleteResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksReadRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksReadResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksSearchRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksSearchResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksUpdateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksUpdateResponseDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/mapper/SlacksMapper.java
  slack/src/test/java/com/msa/fiveio/slack/httpClient/Slacks.http
Labels: refactoring

#133 [Delivery] 배송 생성 로직 리팩토링
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/ExternalServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
  delivery/src/test/java/com/msa/fiveio/delivery/httpClient/Delivery.http
Labels: refactoring

#137 [Order] 주문 삭제 api 생성
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/facade/OrdersFacade.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
  order/src/test/java/com/msa/fiveio/order/httpClient/Orders.http
Labels: feature

#141 [Delivery] 배송 삭제 api 생성
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacade.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryRouteService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryRouteServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRoute.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
  delivery/src/test/java/com/msa/fiveio/delivery/httpClient/Delivery.http
Labels: feature

#145 [Order] Order 관련 로직 리팩토링
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/DeliveryClient.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/dto/response/DeliveryCreateResponseDto.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
Labels: refactoring

#147 [Order] 에러 코드 추가
  common/src/main/java/com/msa/fiveio/common/exception/domain/OrderErrorCode.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/model/entity/Order.java
Labels: feature

#149 [Delivery] 배송 관련 에러코드 추가
  common/src/main/java/com/msa/fiveio/common/exception/domain/DeliveryErrorCode.java
  common/src/main/java/com/msa/fiveio/common/exception/domain/OrderErrorCode.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/ExternalServiceImpl.java
Labels: feature

#153 [Delivery] 배송경로 관련 수정
  Test/IntegrationTest.http
  common/src/main/java/com/msa/fiveio/common/aop/PermissionCheckAspect.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryRouteFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/model/entity/DeliveryRoute.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryRouteController.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/dto/request/DeliveryRouteRequest.java
  gateway/src/main/resources/application.yml
  hub/src/test/java/com/msa/fiveio/hub/httpClient/Hubs.http
Labels: documentation, feature

#151 [Stocks] update Api 추가
  Test/IntegrationTest.http
  common/src/main/java/com/msa/fiveio/common/exception/domain/ProductErrorCode.java
  company/src/main/java/com/msa/fiveio/company/application/facade/CompanysFacadeImpl.java
  product/src/main/java/com/msa/fiveio/product/application/facade/ProductFacade.java
  product/src/main/java/com/msa/fiveio/product/application/facade/ProductFacadeImpl.java
  product/src/main/java/com/msa/fiveio/product/application/facade/StockFacade.java
  product/src/main/java/com/msa/fiveio/product/application/facade/StockFacadeImpl.java
  product/src/main/java/com/msa/fiveio/product/application/usecase/ProductService.java
  product/src/main/java/com/msa/fiveio/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/msa/fiveio/product/application/usecase/StockService.java
  product/src/main/java/com/msa/fiveio/product/application/usecase/StockServiceImpl.java
  product/src/main/java/com/msa/fiveio/product/infrastructure/repository/JPAStocksRepository.java
  product/src/main/java/com/msa/fiveio/product/model/entity/Stocks.java
  product/src/main/java/com/msa/fiveio/product/model/repository/StocksRepository.java
  product/src/main/java/com/msa/fiveio/product/presentation/controller/ProductsController.java
  product/src/main/java/com/msa/fiveio/product/presentation/controller/StocksController.java
  product/src/main/java/com/msa/fiveio/product/presentation/dto/request/ProductCreateRequestDto.java
  product/src/main/java/com/msa/fiveio/product/presentation/dto/request/StockUpdateRequestDto.java
  product/src/main/java/com/msa/fiveio/product/presentation/dto/response/OrderProductGetResponseDto.java
  product/src/main/java/com/msa/fiveio/product/presentation/dto/response/ProductCreateResponseDto.java
  product/src/main/java/com/msa/fiveio/product/presentation/dto/response/StockUpdateResponseDto.java
  product/src/main/java/com/msa/fiveio/product/presentation/mapper/ProductsMapper.java
  product/src/main/java/com/msa/fiveio/product/presentation/mapper/StocksMapper.java
Labels: feature

#157 [Slack] Slack 공통기능 추가
  ai/src/main/java/com/msa/fiveio/ai/presentation/dto/AisCreateRequestDto.java
  gateway/src/main/resources/application.yml
  slack/build.gradle
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacade.java
  slack/src/main/java/com/msa/fiveio/slack/application/facade/SlacksFacadeImpl.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksService.java
  slack/src/main/java/com/msa/fiveio/slack/application/usecase/SlacksServiceImpl.java
  slack/src/main/java/com/msa/fiveio/slack/model/entity/Slacks.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/controller/SlacksController.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksCreateRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksSearchRequestDto.java
  slack/src/main/java/com/msa/fiveio/slack/presentation/dto/SlacksUpdateRequestDto.java
  slack/src/main/resources/application.yml
  slack/src/test/java/com/msa/fiveio/slack/httpClient/Slacks.http
Labels: feature

#159 [User] 배송담당자 생성
  common/src/main/java/com/msa/fiveio/common/exception/domain/UserErrorCode.java
  gateway/src/main/java/com/spring_cloud/client/gateway/CustomPreFilter.java
  user/src/main/java/com/msa/fiveio/user/application/DeliveryManagerService.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/JwtAuthenticationFilter.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/JwtUtil.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/repository/JpaDeliveryManagerRepository.java
  user/src/main/java/com/msa/fiveio/user/model/entity/DeliveryManagers.java
  user/src/main/java/com/msa/fiveio/user/model/entity/DeliveryManagersFactory.java
  user/src/main/java/com/msa/fiveio/user/model/entity/enums/ManagersTypeEnum.java
  user/src/main/java/com/msa/fiveio/user/model/repository/DeliveryManagerRepository.java
  user/src/main/java/com/msa/fiveio/user/presentation/controller/DeliveryManagerController.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/DeliveryManagerProfileDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/DeliveryManagerRequestDto.java
  user/src/test/java/com/msa/fiveio/user/Users.http
Labels: feature

#161 [User] 회원가입 수정 및 조회 추가 / jwt 헤더 수정
  user/src/main/java/com/msa/fiveio/user/application/UsersService.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/jwt/UserDetailsServiceImpl.java
  user/src/main/java/com/msa/fiveio/user/model/entity/Users.java
  user/src/main/java/com/msa/fiveio/user/model/entity/UsersFactory.java
  user/src/main/java/com/msa/fiveio/user/model/repository/UsersRepository.java
  user/src/main/java/com/msa/fiveio/user/presentation/controller/UsersController.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UserDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersProfileDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersSignUpRequestDto.java
Labels: refactoring

#164 [Order] 주문 취소 시 관련된 배송 정보 삭제 기능
  common/src/main/java/com/msa/fiveio/common/exception/domain/OrderErrorCode.java
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/DeliveryClient.java
  order/src/test/java/com/msa/fiveio/order/httpClient/Orders.http
Labels: feature

#166 [Delivery] 배송 취소 api 구현
  common/src/main/java/com/msa/fiveio/common/exception/domain/DeliveryErrorCode.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacade.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/facade/DeliveryFacadeImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/msa/fiveio/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
Labels: feature

#167 [Bug] 권한설정 및 Swagger 설정
  gateway/src/main/resources/application.yml
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubRouteController.java
  hub/src/main/java/com/msa/fiveio/hub/presentation/controller/HubsController.java
  product/src/main/java/com/msa/fiveio/product/ProductApplication.java
  product/src/main/java/com/msa/fiveio/product/presentation/controller/ProductsController.java
  product/src/main/java/com/msa/fiveio/product/presentation/controller/StocksController.java
  user/src/main/java/com/msa/fiveio/user/infrastructure/configuration/SwaggerConfig.java
  user/src/main/java/com/msa/fiveio/user/presentation/controller/DeliveryManagerController.java
Labels: bug, refactoring

#169 [Order, Delivery] Order 및 Delivery api 권한 설정
  delivery/src/main/java/com/msa/fiveio/delivery/presentation/controller/DeliveryController.java
  order/src/main/java/com/msa/fiveio/order/presentation/controller/OrdersController.java
Labels: feature

#172 [Order] 재고 요청 수정
  order/src/main/java/com/msa/fiveio/order/application/facade/OrderFacadeImpl.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalService.java
  order/src/main/java/com/msa/fiveio/order/application/usecase/ExternalServiceImpl.java
  order/src/main/java/com/msa/fiveio/order/infrastructure/client/ProductClient.java
  product/src/main/java/com/msa/fiveio/product/presentation/controller/ProductsController.java
Labels: bug

#170 [User] 배송담당자 조회
  user/src/main/java/com/msa/fiveio/user/application/DeliveryManagerService.java
  user/src/main/java/com/msa/fiveio/user/model/entity/DeliveryManagersFactory.java
  user/src/main/java/com/msa/fiveio/user/presentation/controller/DeliveryManagerController.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/DeliveryManagerGetDto.java
  user/src/main/java/com/msa/fiveio/user/presentation/dto/UsersProfileDto.java
  user/src/test/java/com/msa/fiveio/user/httpClient/Users.http
Labels: feature

#173 [Document] READ ME 추가
  README.md
Labels: documentation
